/**
 * E2E tests: crossword page — grid rendering, clue accuracy, interaction, solve/clear.
 */

const { test, expect } = require('@playwright/test');
const { startCrossword } = require('./helpers');

test.describe('Crossword page structure', () => {

    test('crossword page shows grid, clues panels, and progress bar', async ({ page }) => {
        await startCrossword(page);
        await expect(page.locator('#crossword')).toBeVisible();
        // Clue panels: at least one direction must have clues rendered
        // (both panels exist in DOM but one may be empty if layout placed all words one way)
        const acrossHasClues = await page.locator('#across_questions .crossword_questions_css').count() > 0;
        const downHasClues   = await page.locator('#down_questions .crossword_questions_css').count() > 0;
        expect(acrossHasClues || downHasClues).toBe(true);
        // Progress bar element exists (it may have width 0 at start)
        await expect(page.locator('#crossword_progress')).toBeAttached();
    });

    test('grid contains input cells with an "ans" attribute', async ({ page }) => {
        await startCrossword(page);
        const cellCount = await page.locator('input.crossword_cells').count();
        expect(cellCount).toBeGreaterThan(0);

        // Every cell must have a non-empty ans attribute (the correct letter)
        const badCells = await page.evaluate(() =>
            Array.from(document.querySelectorAll('input.crossword_cells'))
                .filter(el => !el.getAttribute('ans') || el.getAttribute('ans').trim() === '')
                .length
        );
        expect(badCells).toBe(0);
    });

    test('at least one across clue is rendered', async ({ page }) => {
        await startCrossword(page);
        const acrossCount = await page.locator('#across_questions span.crossword_questions_css').count();
        const downCount   = await page.locator('#down_questions span.crossword_questions_css').count();
        // At least one direction must have clues (crossword may be all-across or mixed)
        expect(acrossCount + downCount).toBeGreaterThan(0);
    });

    test('each clue span has non-empty question text', async ({ page }) => {
        await startCrossword(page);
        const emptyClues = await page.evaluate(() =>
            Array.from(document.querySelectorAll('.crossword_questions_css'))
                .filter(el => !el.getAttribute('question') || el.getAttribute('question').trim() === '')
                .length
        );
        expect(emptyClues).toBe(0);
    });

    test('each clue span has a non-empty answer attribute', async ({ page }) => {
        await startCrossword(page);
        const badClues = await page.evaluate(() =>
            Array.from(document.querySelectorAll('.crossword_questions_css'))
                .filter(el => !el.getAttribute('answer') || el.getAttribute('answer').trim() === '')
                .length
        );
        expect(badClues).toBe(0);
    });

});

test.describe('Clue–answer integrity', () => {

    test('clue text matches question field in xy_to_data', async ({ page }) => {
        await startCrossword(page);

        // Collect all clue spans: {question, answer}
        const clueSpans = await page.evaluate(() =>
            Array.from(document.querySelectorAll('.crossword_questions_css')).map(el => ({
                question: el.getAttribute('question'),
                answer:   el.getAttribute('answer'),
            }))
        );

        // Each entry in xy_to_data also has a clue field — check they align
        const xyEntries = await page.evaluate(() =>
            Object.values(xy_to_data).map(d => ({ clue: d.clue, answer: d.answer }))
        );

        // Every clue span's question must appear somewhere in xy_to_data clues
        for (const span of clueSpans) {
            const found = xyEntries.some(e => e.clue === span.question);
            expect(found, `Clue "${span.question}" not found in xy_to_data`).toBe(true);
        }
    });

    test('answer attribute on clue span matches the letters in the grid cells', async ({ page }) => {
        await startCrossword(page);

        // Pick the first clue span
        const firstClue = await page.evaluate(() => {
            const el = document.querySelector('.crossword_questions_css');
            if (!el) return null;
            return {
                answer:      el.getAttribute('answer'),
                startx:      parseInt(el.getAttribute('startx')),
                starty:      parseInt(el.getAttribute('starty')),
                orientation: el.getAttribute('orientation'),
            };
        });

        if (!firstClue) { test.skip(); return; }

        // Cell IDs are generated by id_of_cell_alone(col, row) → 'crossword_cells__${col}_${row}'
        const cellLetters = await page.evaluate(({ startx, starty, orientation, answer }) => {
            const letters = [];
            for (let i = 0; i < answer.length; i++) {
                const col = orientation === 'across' ? startx + i : startx;
                const row = orientation === 'across' ? starty     : starty + i;
                const el  = document.getElementById(`crossword_cells__${col}_${row}`);
                if (el) letters.push(el.getAttribute('ans') || '');
            }
            return letters.join('');
        }, firstClue);

        expect(cellLetters).toBe(firstClue.answer);
    });

    test('clue question text is visible in the clues panel', async ({ page }) => {
        await startCrossword(page);

        // Get the first clue's question text
        const firstQuestion = await page.evaluate(() => {
            const el = document.querySelector('.crossword_questions_css');
            return el ? el.getAttribute('question') : null;
        });

        if (!firstQuestion) { test.skip(); return; }

        // That question text should appear in the rendered HTML of the clues panel
        const panelText = await page.locator('.clues-container').textContent();
        expect(panelText).toContain(firstQuestion);
    });

});

test.describe('Crossword interaction', () => {

    test('typing a correct letter in a cell is accepted', async ({ page }) => {
        await startCrossword(page);

        // Get the first cell's id and correct letter
        const { cellId, correctLetter } = await page.evaluate(() => {
            const el = document.querySelector('input.crossword_cells');
            return { cellId: el.id, correctLetter: el.getAttribute('ans') };
        });

        await page.locator(`#${cellId}`).click();
        await page.locator(`#${cellId}`).fill(correctLetter);

        const value = await page.locator(`#${cellId}`).inputValue();
        expect(value.toUpperCase()).toBe(correctLetter.toUpperCase());
    });

    test('input is converted to uppercase automatically', async ({ page }) => {
        await startCrossword(page);

        const cellId = await page.evaluate(() => document.querySelector('input.crossword_cells').id);
        await page.locator(`#${cellId}`).click();
        await page.locator(`#${cellId}`).fill('a');

        const value = await page.locator(`#${cellId}`).inputValue();
        expect(value).toMatch(/^[A-Z]$/);
    });

    test('progress bar advances when cells are filled', async ({ page }) => {
        await startCrossword(page);

        const before = await page.locator('#crossword_progress').evaluate(el => parseFloat(el.style.width) || 0);

        // Fill in the first correct letter
        const { cellId, correctLetter } = await page.evaluate(() => {
            const el = document.querySelector('input.crossword_cells');
            return { cellId: el.id, correctLetter: el.getAttribute('ans') };
        });
        await page.locator(`#${cellId}`).click();
        await page.locator(`#${cellId}`).fill(correctLetter);
        await page.waitForTimeout(200); // debounced updateProgress

        const after = await page.locator('#crossword_progress').evaluate(el => parseFloat(el.style.width) || 0);
        expect(after).toBeGreaterThan(before);
    });

    test('clicking a clue highlights it as active', async ({ page }) => {
        await startCrossword(page);

        const firstClue = page.locator('.crossword_questions_css').first();
        await firstClue.click();

        await expect(firstClue).toHaveClass(/active-clue/);
    });

    test('Solve All fills every cell with the correct letter', async ({ page }) => {
        await startCrossword(page);

        // Accept the confirm dialog
        page.on('dialog', dialog => dialog.accept());
        await page.click('button:has-text("Solve All")');

        // All cells should now have a value matching their ans attribute
        const mismatch = await page.evaluate(() =>
            Array.from(document.querySelectorAll('input.crossword_cells'))
                .filter(el => el.value.toUpperCase() !== (el.getAttribute('ans') || '').toUpperCase())
                .length
        );
        expect(mismatch).toBe(0);
    });

    test('progress text shows 100% after Solve All', async ({ page }) => {
        await startCrossword(page);
        page.on('dialog', dialog => dialog.accept());
        await page.click('button:has-text("Solve All")');
        await page.waitForTimeout(200);
        await expect(page.locator('#progress_text')).toHaveText('100% Complete');
    });

    test('Clear button empties all cells', async ({ page }) => {
        await startCrossword(page);

        // First solve, then clear
        page.on('dialog', dialog => dialog.accept());
        await page.click('button:has-text("Solve All")');
        await page.click('button:has-text("Clear")');

        const filledCount = await page.evaluate(() =>
            Array.from(document.querySelectorAll('input.crossword_cells'))
                .filter(el => el.value.trim() !== '').length
        );
        expect(filledCount).toBe(0);
    });

});
